// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/auth/callback" | "/hive-setup" | "/hives" | "/hives/[hiveId]" | "/hives/[hiveId]/conversations/[conversationId]" | "/hives/[hiveId]/conversations/[conversationId]/listen" | "/hives/[hiveId]/conversations/[conversationId]/report" | "/hives/[hiveId]/conversations/[conversationId]/respond" | "/hives/[hiveId]/conversations/[conversationId]/result" | "/hives/[hiveId]/conversations/[conversationId]/understand" | "/hives/[hiveId]/conversations/[conversationId]/vote" | "/hives/[hiveId]/invite" | "/hives/[hiveId]/members" | "/hives/[hiveId]/settings" | "/members" | "/profile-setup" | "/settings" | "/welcome"
type AppRouteHandlerRoutes = "/api/conversations" | "/api/conversations/[conversationId]" | "/api/conversations/[conversationId]/analyze" | "/api/conversations/[conversationId]/attachments" | "/api/conversations/[conversationId]/feedback" | "/api/conversations/[conversationId]/phase" | "/api/conversations/[conversationId]/report" | "/api/conversations/[conversationId]/responses" | "/api/conversations/[conversationId]/upload" | "/api/conversations/[conversationId]/votes" | "/api/hives" | "/api/hives/[hiveId]" | "/api/hives/[hiveId]/invite" | "/api/last-hive" | "/api/responses/[responseId]/like"
type PageRoutes = never
type LayoutRoutes = "/" | "/hives/[hiveId]" | "/hives/[hiveId]/conversations/[conversationId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/api/conversations": {}
  "/api/conversations/[conversationId]": { "conversationId": string; }
  "/api/conversations/[conversationId]/analyze": { "conversationId": string; }
  "/api/conversations/[conversationId]/attachments": { "conversationId": string; }
  "/api/conversations/[conversationId]/feedback": { "conversationId": string; }
  "/api/conversations/[conversationId]/phase": { "conversationId": string; }
  "/api/conversations/[conversationId]/report": { "conversationId": string; }
  "/api/conversations/[conversationId]/responses": { "conversationId": string; }
  "/api/conversations/[conversationId]/upload": { "conversationId": string; }
  "/api/conversations/[conversationId]/votes": { "conversationId": string; }
  "/api/hives": {}
  "/api/hives/[hiveId]": { "hiveId": string; }
  "/api/hives/[hiveId]/invite": { "hiveId": string; }
  "/api/last-hive": {}
  "/api/responses/[responseId]/like": { "responseId": string; }
  "/auth/callback": {}
  "/hive-setup": {}
  "/hives": {}
  "/hives/[hiveId]": { "hiveId": string; }
  "/hives/[hiveId]/conversations/[conversationId]": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/listen": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/report": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/respond": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/result": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/understand": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/conversations/[conversationId]/vote": { "hiveId": string; "conversationId": string; }
  "/hives/[hiveId]/invite": { "hiveId": string; }
  "/hives/[hiveId]/members": { "hiveId": string; }
  "/hives/[hiveId]/settings": { "hiveId": string; }
  "/members": {}
  "/profile-setup": {}
  "/settings": {}
  "/welcome": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/hives/[hiveId]": never
  "/hives/[hiveId]/conversations/[conversationId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
